/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programa;

import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lujop
 */
public class Entrevistas extends javax.swing.JPanel {

    public static DefaultTableModel modeloEntre;
    
    
    public Entrevistas() {
        initComponents();
        modeloEntre = (DefaultTableModel) this.agendaEntrevista.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        baseEntrevista = new javax.swing.JPanel();
        paneltablaEntrevista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        agendaEntrevista = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(720, 470));

        jButton1.setText("Imprimir");

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        baseEntrevista.setBackground(new java.awt.Color(102, 204, 0));
        baseEntrevista.setLayout(new java.awt.BorderLayout());

        paneltablaEntrevista.setBackground(new java.awt.Color(255, 51, 102));

        agendaEntrevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.I. Alumno", "Alumno", "Entrevistador", "C.I. Entrevistador", "Fecha y hora", "Lugar"
            }
        ));
        jScrollPane1.setViewportView(agendaEntrevista);

        javax.swing.GroupLayout paneltablaEntrevistaLayout = new javax.swing.GroupLayout(paneltablaEntrevista);
        paneltablaEntrevista.setLayout(paneltablaEntrevistaLayout);
        paneltablaEntrevistaLayout.setHorizontalGroup(
            paneltablaEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        paneltablaEntrevistaLayout.setVerticalGroup(
            paneltablaEntrevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        baseEntrevista.add(paneltablaEntrevista, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(baseEntrevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(baseEntrevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EntrevistaEdit pred = new EntrevistaEdit(); 
        baseEntrevista.removeAll(); //se quita todo lo que esta en la base
        pred.setMinimumSize(new Dimension(200, 500));
        paneltablaEntrevista.setPreferredSize(new Dimension(800, 500));
        //baseAlumnos.setLayout(new FlowLayout());
        BoxLayout boxlayout = new BoxLayout(baseEntrevista, BoxLayout.X_AXIS);
        baseEntrevista.setLayout(boxlayout);
        
        baseEntrevista.add(paneltablaEntrevista);
        baseEntrevista.add(pred);
        
        
        Base base = (Base)this.getRootPane().getParent();
        base.setMinimumSize(new Dimension(1000,600));
        base.setLocationRelativeTo(null);
        base.repaint();
        base.revalidate();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable agendaEntrevista;
    private javax.swing.JPanel baseEntrevista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneltablaEntrevista;
    // End of variables declaration//GEN-END:variables
}
