
package programa;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author karly
 */
public class Periodo extends javax.swing.JPanel {

    /**
     * Creates new form periodo
     */
    String resu;
    public Periodo() {
        initComponents();
        DateFormat dateFormatMain = new SimpleDateFormat("yyyy");
        String dateMain = dateFormatMain.format(new Date());
        text.setText(dateMain);
        DateFormat dateFormat = new SimpleDateFormat("d MMMM yyyy");
        String date = dateFormat.format(new Date());
        fechaInicio.setText(date);
        
       
   
//        result.setText(resultado(text.getText(), (String) cr.getSelectedItem()));
        
    }
    
    private String resultado(String ano, String combo) {
        resu = ano +"-"+ combo;
        return resu;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cr = new javax.swing.JComboBox<>();
        text = new javax.swing.JTextField();
        fechaInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de Periodo");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        cr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CR chooser", "1CR", "2CR", "3CR", "4CR" }));
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });
        add(cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });
        add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        fechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaInicioActionPerformed(evt);
            }
        });
        add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel2.setText("Introducir periodo Académico:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 70, -1));

        jLabel3.setText("Fecha en la que se está iniciando el registro de periodo académico");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 360, -1));

        jLabel4.setText("Resultado:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        guardar.setText("Guardar Periodo");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void fechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaInicioActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_resultActionPerformed

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
        // TODO add your handling code here:
        if(cr.getSelectedItem().equals("CR chooser")){
           // JOptionPane.showMessageDialog(result,"Escoja un periodo cr");
            result.setText("");
            
        }
        else{result.setText(resultado(text.getText(), (String) cr.getSelectedItem()));}
    }//GEN-LAST:event_crActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        try {
            if (!result.getText().isEmpty()) {
                //String status = "En proceso";
                String addSql = String.format("INSERT INTO Periodos (periodo, status, inicio, final) VALUES"
                        + "('" + result.getText()
                        + "','" + false + "','" + fechaInicio.getText() + "','" + " " + "') ");
                objConexion.ejecutarSentenciaSQl(addSql);
                //objConexion.cerrarConexion();
                objConexion.cerrarConexion();
                Base base = new Base();
                base.cerrarVentana();
            } else {
                JOptionPane.showMessageDialog(result, "Escoja un periodo cr");
            }
        } catch (Exception e) {
            System.out.println("hello no funca");
        }
//        Base.disp        
        objConexion.cerrarConexion();
    }//GEN-LAST:event_guardarActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        conexion objConexion = new conexion();
        try{
            if (!result.getText().isEmpty()) {
            //String status = "En proceso";
            String sql = "DELETE FROM Periodos WHERE inicio = '" + fechaInicio.getText() +"'";
                objConexion.ejecutarSentenciaSQl(sql);
            //objConexion.cerrarConexion();
            } else {
            JOptionPane.showMessageDialog(result,"Escoja un periodo cr");}
        }          catch(Exception e){System.out.println("hello no funca");}
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cr;
    private javax.swing.JTextField fechaInicio;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField result;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
