/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programa;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author lujop
 */
public class Presentacion extends javax.swing.JPanel {

    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImprimirPresentacion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        basePresentacion = new javax.swing.JPanel();
        paneltablapresentacion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPresentacion = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(720, 470));

        ImprimirPresentacion.setText("Imprimir");

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        basePresentacion.setLayout(new java.awt.BorderLayout());

        tablaPresentacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alumno", "C.I. Alumno", "Jurado", "C.I. Jurado", "Fecha y hora", "Lugar"
            }
        ));
        jScrollPane1.setViewportView(tablaPresentacion);

        javax.swing.GroupLayout paneltablapresentacionLayout = new javax.swing.GroupLayout(paneltablapresentacion);
        paneltablapresentacion.setLayout(paneltablapresentacionLayout);
        paneltablapresentacionLayout.setHorizontalGroup(
            paneltablapresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        paneltablapresentacionLayout.setVerticalGroup(
            paneltablapresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        basePresentacion.add(paneltablapresentacion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ImprimirPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(basePresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImprimirPresentacion)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basePresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PresentacionEdit pred = new PresentacionEdit(); 
        basePresentacion.removeAll(); //se quita todo lo que esta en la base
        pred.setMinimumSize(new Dimension(200, 500));
        paneltablapresentacion.setPreferredSize(new Dimension(800, 500));
        //baseAlumnos.setLayout(new FlowLayout());
        BoxLayout boxlayout = new BoxLayout(basePresentacion, BoxLayout.X_AXIS);
        basePresentacion.setLayout(boxlayout);
        
        basePresentacion.add(paneltablapresentacion);
        basePresentacion.add(pred);
        
        
        Base base = (Base)this.getRootPane().getParent();
        base.setMinimumSize(new Dimension(1000,600));
        base.setLocationRelativeTo(null);
        base.repaint();
        base.revalidate();
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ImprimirPresentacion;
    private javax.swing.JPanel basePresentacion;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneltablapresentacion;
    private javax.swing.JTable tablaPresentacion;
    // End of variables declaration//GEN-END:variables
}
